blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions for nekowarden
    url: https://github.com/nekowarden/server/discussions
    about: An alternative to the Discourse forum, if this is easier for you.
